### ISSUE TITLE
Support for Fedora 32

### ISSUE THREAD

**Issue by jovandeginste** [Fedict/eid-archive#5]
Fedora 32 has been released ([change set](https://fedoraproject.org/wiki/Releases/32/ChangeSet)). Please add a version level for `32` in the repository [folder](http://files.eid.belgium.be/rpm/fedora/).

Thanks!

**Comment by yoe** [comment]
Yes, we're aware of that; the packages have already been built and are waiting in the "candidate" repository for someone to go to the office, take the smartcard with the signing key out of the safe, and plug it into the correct machine. Normally this is a few minutes worth of work, but due to the whole Corona situation, this is obviously taking a bit longer than usual. Please bear with us as we get this sorted.

Thanks.

**Comment by yoe** [comment]
Repositories have been updated, the Fedora 32 repository is now live. The eid.belgium.be website still needs to be updated to reflect the change, but that's not necessary to use it, so closing this issue.
